name: Build kernel (gcc)

on:
  workflow_dispatch:

env:
  Kernel_Link: https://github.com/claud-wait/Neternels-M10
  GCC: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Clone
         run: |
              sudo apt update && sudo apt install git wget make ccache zip -y
              cd && git clone --depth=1 $Kernel_Link kernel && cd kernel
              git clone --depth=1 $GCC /opt/gcc
              bash build_kernel.sh

       - name: Upload to Release
         uses: softprops/action-gh-release@v1
         with:
           files: /home/runner/kernel/neternelQ-m10.zip        
           name: neternel for M10         
           tag_name: ${{ github.run_id }}
           permissions:
             contents: write
           body: |
             neternel kernel
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
